# This is a basic workflow to help you get started with Actions

name: CI

on:

  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run unit tests
        run: ./gradlew test

  heroku_deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_KEY
          EOF
        env:
          HEROKU_KEY: ${{ secrets.HEROKU_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

      - name: Add Heroku remote
        run: heroku git:remote -a $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

      - name: Push to Heroku
        run: git push -f heroku master